name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install package dependencies
        run: sudo apt-get install build-essential git python3-dev python3-venv python3-cairo-dev python3-gi-cairo libgirepository1.0-dev libcairo2-dev libpango1.0-dev gir1.2-webkit2-4.0 pkg-config

      - name: Install beeware tools
        run: python -m pip install briefcase

      - name: Install app dependencies
        env:
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: briefcase dev --no-run
        shell: bash

      - name: Create android scaffold
        env:
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: briefcase create android
        shell: bash

      - name: Build app
        run: briefcase build android
        shell: bash

#      - name: Package app
#        run: briefcase package android gradle # For *.aab package format
#        shell: bash

      - name: Upload build apk
        uses: actions/upload-artifact@v3
        with:
          name: testapp_debug
          path: ./build/testapp/android/gradle/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

